spring.application.name=MiniS3Master
server.port=8080

# Logging
logging.level.root=INFO

# dev
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

# database
spring.datasource.url=jdbc:sqlite:minis3.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.community.dialect.SQLiteDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration