spring.application.name=MiniS3Worker
server.port=8081

# Logging
logging.level.root=INFO

# Storage
storage.root=data
spring.servlet.multipart.enabled=false

# dev
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true